using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyVersionAttribute("0.0.1.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1.1")]
[assembly: AssemblyTitleAttribute("SimpleTemplate")]
[assembly: AssemblyDescriptionAttribute("Template file transformation")]
[assembly: AssemblyCopyrightAttribute("No copyright")]

